routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'TestController@welcome');

Route::get('/curso/{id}', 'CursoController@show'); //
Route::get('/categoria/{id}', 'CursoCatController@show');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


//Editar datos usuario

Route::middleware(['auth'])->prefix('User')->namespace('User')->group(function (){
    
    Route::get('/cuenta', 'UserController@index');
    Route::post('/cuenta/{id}/update', 'UserController@update');

    Route::get('/cuenta/cambioclave', 'UserController@ChangePassword_index');
    Route::post('/cuenta/cambioclave', 'UserController@ChangePassword_store');

    Route::get('/cuenta/foto', 'UserController@image');
    Route::post('/cuenta/foto', 'UserController@storedpic');
    
    Route::get('/miscursos', 'CursoController@showlist');
    Route::get('/graficodenotas', 'GraficoController@index');
    Route::post('{id}/inscribirme', 'CursoController@register');

    Route::get('/miscursos/{id}/Modulos', 'CursoController@detail');
    Route::get('/miscursos/Modulos/Videos', 'CursoController@detail');
    

    

});

   /*Estas dos rutas deben estar dentro del prefijo user, por el momento estan aqui, pero debes recordar cambiarlas a donde van*/
   Route::get('cuenta/redes', 'RedesUsuariosController@show');
   Route::get('cuenta/redes/update', 'RedesUsuariosController@update');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Carbon\Carbon;

class User extends Authenticatable
{

    // Relaciones del modelo

     public function roles()
    {
        return $this->belongsTo(Roles::class); //Un curso pertenece a una categoria 
    } 

        public function Cursos()
    {
        return $this->hasMany(Curso::class); //Un curso tiene muchos modulos 
    }

        public function ModuloAsesor()
    {
        return $this->hasMany(Modulos::class); //Un curso tiene muchos modulos 
    }

        public function Notas()
    {
        return $this->hasMany(Notas::class); //Un curso tiene muchos modulos 
    }

         public function certificados()
    {
        return $this->hasMany(Certificado::class); //Un curso tiene muchos certificados 
    }

      public function CursosUser()
    {
        return $this->hasMany(CursoUser::class); //Un curso tiene muchos modulos 
    }

     public function RedesUsuarios()
    {
        return $this->HasMany(RedesUsuarios::class); //Un curso pertenece a una categoria 
    } 

    // Fin de las relaciones 

   
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','user_roles_id','ci'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];


    public function getImageUrlAttribute()
    {
        
        $image= $this->image; 

        if($image){
            $image= '/images/img-perfil/'.$image; 
           return $image; //url = Accesor definido en el modelo ProductImage
        
               }
        //default
        return '/images/default.jpg';
    }


     public function getAgeAttribute()
    {
               
        $fecha= $this->birth;
        $edad= Carbon::parse($fecha)->age;

        return $edad; 
    }


   
}

app/Http/Controllers/User/CursoController.php
<?php

namespace App\Http\Controllers\User;

use Mail;
use App\Mail\CursosRegister;
use App\Curso;
use App\Modulos;
use App\Videos;
use App\User; 
use App\CursoUser;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class CursoController extends Controller
{
    
     

      public function showlist()
    {
        $id = auth()->user()->id; 
        $curso = CursoUser::where('user_id',$id)->where('aceptado',1)->get();

        return view('user.cursos.list')->with(compact('curso'));
    }

    public function register (Request $request, $id) {

    	$CursoUser = new CursoUser();
        $CursoUser->user_id = auth()->user()->id; 
        $CursoUser->curso_id = $id;
        $CursoUser->fechainscri = now();
        $CursoUser->aceptado = 0;
        $CursoUser->save();


        $Curso = Curso::find($id); 
        $User = auth()->user();
        $Reason = $request->input('why');
        $Ntarjeta = $request->input('Ntarjeta');
        $Nbtarjeta = $request->input('Nbtarjeta');
    	$admins = User::where('roles_id', 1)->get();

        Mail::to($admins)->send(new CursosRegister ($User, $Curso , $Ntarjeta,$Nbtarjeta, $Reason ));
            
        $notification = 'Hemos enviado tu solicitud, recibiras noticias de nosotros pronto!';
        return back()->with(compact('notification'));


    }

    public function detail (Request $request, $id){

        $Curso   = Curso::find($id); 
        $Modulos = Modulos::where('curso_id','=',$id)->paginate(2);
        $Videos  = Videos::where('modulos_id',1) -> get(); 


    $view = View('user.cursos.video')->with(compact('Modulos', 'Curso','Videos'));

        if($request->ajax()){

            $id2 = $request->input("id");
            $video  = Videos::where('modulos_id',$id2)->get(); 
            $view = View('user.cursos.video')->with('Videos',$video);
            $sections = $view->renderSections();
            return Response::json($sections['contentPanel']); 
        }

        else return $view;



    }

    
}

app/Http/Controllers/User/GraficoController.php
<?php

namespace App\Http\Controllers\User;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;
use App\notas;


class GraficoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
          $notas = notas::all();
          return view('user.cursos.grafico')->with(compact('notas'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\notas  $notas
     * @return \Illuminate\Http\Response
     */
    public function show(notas $notas)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\notas  $notas
     * @return \Illuminate\Http\Response
     */
    public function edit(notas $notas)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\notas  $notas
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, notas $notas)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\notas  $notas
     * @return \Illuminate\Http\Response
     */
    public function destroy(notas $notas)
    {
        //
    }
}

app/Http/Controllers/User/RedesUsuariosController.php
<?php

namespace App\Http\Controllers;

use App\RedesUsuarios;
use App\User;
use App\Redes;
use Illuminate\Http\Request;

class RedesUsuariosController extends Controller
{


    public function show (Request $request) {

        $id = $request->input("id");
        $userauth = auth()->user()->id;
        $user = User::find($userauth);
        $red = Redes::find($id); 
        $datosredes = RedesUsuarios::where('user_id', '=', $user->id)
                       ->where('red_id', '=',  $id)
                       ->get();
         

       $redphoto = '/images/img-red/'.$red['button'] ;      
       foreach ($datosredes as $datos) {

            $link = $datos->link;  
            $idred = $datos->id;         
        }   

              

        if (!empty($link)){ return response()->json(['success'=>  $link,'redname'=> $red['nombre'], 'id'=> $idred ,'redfoto' => $redphoto]); }

        else{ return response()->json(['success'=> $red['link'],'redname'=> $red['nombre'], 'id'=> $id , 'redfoto' => $redphoto]);}
        
    }


    public function update (Request $request){

      $id2 = $request->input("id");
      $link2 = $request->input("link");
      $userauth = auth()->user()->id;
      $user = User::find($userauth);

     $datosredes2 = RedesUsuarios::where('user_id', '=', $user->id)
                       ->where('red_id', '=',  $id2)
                       ->get();

     foreach ($datosredes2 as $datos) {

            $link3 = $datos->link;  
                   
    }   
     

      if (!empty($link3)) {


       $redes= RedesUsuarios::find($id2);
       $redes->link = $link2;
       $redes->save(); 

        


      }

      else {

        $redes = new RedesUsuarios();
        $redes->link = $link2;
        $redes->user_id = $user->id; 
        $redes->red_id = $id2; 
        $redes->save(); //EJECUTA INSERT SOBRE LA TABLA DE REDES

        

      }

       return response()->json(['success'=>'Datos Actualizados con exito' ]); 

    }


    
}

app/Http/Controllers/User/UserController.php
<?php

namespace App\Http\Controllers\User;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;
use App\User;
use App\Redes;
use Hash;


class UserController extends Controller
{
    
    public function index()
    {

        $userauth = auth()->user()->id;
        $user = User::find($userauth);
        $redes = Redes::all(); 

       
    
        return view('User.index')->with(compact('user' , 'redes'));
    }

  
   public function image()
    {

        $userauth = auth()->user()->id;
        $user = User::find($userauth);
        
    
        return view('User.Image.index')->with(compact('user'));
    }


    public function update(Request $request, $id)
    {

        //validar
        $messages = [
            'name.required' => 'Es necesario ingresar un nombre .',
            'name.max' => 'El nombre debe tener como máximo 255 caracteres.',
            'last.required' => 'Es necesario ingresar un apellido .',
            'last.max' => 'El Apellido debe tener como máximo 255 caracteres.',
            'tel.max' =>  'El telefono debe tener maximo 13 caracteres.',
            'gender.required' => 'Debe seleccionar su sexo',          
            'email.required' => 'El campo E-mail es requerido.',
            'email.email' => 'El formato del correo electrónico no es correcto.',
            'email.max' => 'El correo electrónico debe tener como máximo 255 caracteres.',
            'email.unique' => 'El correo electrónico ya se encuentra registrado.',
           
        ];
        
        $rules = [
            'name' => 'required|string|max:255',
            'last'  => 'required|string|max:255',
            'gender' => 'required',
            'tel'  => 'max:13',
            'email' => 'required|string|email|max:255|unique:users,email,'.$id,

            
        ];
        
        $this->validate($request, $rules, $messages );//validar

        $user = User::find($id);
        $user->name = $request->input('name');
        $user->lastname = $request->input('last');
        $user->phone = $request->input('tel');
        $user->birth = $request->input('date');
        $user->email = $request->input('email');
        $user->edad = $user->Age; 
        $user->gender = $request->input('gender');
        $user->ci = $request->input('ci');
        $user->update(); //EJECUTA Update SOBRE LA TABLA DE usuarios

        $notification = "Se han actualizado los datos del cliente satisfactoriamente.";
        return back()->with(compact('notification'));
       
    }

     public function storedpic(Request $request)
    {
         $userauth = auth()->user()->id;
         $user = User::find($userauth);
         $user->description = $request->input('description');  
         $user->update(); //EJECUTA Update SOBRE LA TABLA DE usuarios

        if ($request->file('foto') != null ) {

                      //Guardar la img en nuestro proyecto
                $file = $request->file('foto');
                $path = public_path() . '/images/img-perfil';
                $filename = uniqid() . $file->getClientOriginalName();
                $moved = $file->move($path, $filename);
                
                //Crear 1 registro en la tabla product_images
                if ($moved) {

                $userauth = auth()->user()->id;
                $user = User::find($userauth);
                $user->image = $filename;
                $user->update(); //EJECUTA Update SOBRE LA TABLA DE usuarios
               

                }
                else{

                        $error = "No se ha podido actualizar la foto ";
                        return back()->with(compact('alert'));
                     

                }

                $notification = "Se han actualizado los datos satisfactoriamente.";
                return back()->with(compact('notification'));
            

        }

        else{
                if( $request->input('description') != null ){

                         $alert = "Se actualizo la descripción, no ha actualizado la foto ";
                        return back()->with(compact('alert'));
                    }

                    else{

                         $alert = "No ha realizado cambios ";
                         return back()->with(compact('alert'));
                    }

                
            
            }
      
        
        return back();
    }




    public function ChangePassword_index()
    {
        return view('User.changePassword_index');
    }

    public function ChangePassword_store(Request $request)
    {
        //validar
        $messages = [
            'password.required' => 'El campo de contraseña actual es requerido.',
            'newpassword.required' => 'Por favor ingrese la nueva contraseña.',
            'newpassword.min' => 'La nueva contraseña debe tener al menos 6 caracteres.',
            'password_confirmation.required' => 'Por favor ingrese la confirmación de la contraseña.',
            'password_confirmation.same' => 'Las contraseñas no son iguales, por favor verifique.'
            
        ];
        
        $rules = [
            'password' => 'required',
            'newpassword' => 'required|string|min:6',
            'password_confirmation' => 'required|same:newpassword'
            
        ];
        
        $this->validate($request, $rules, $messages );//validar

        $password = auth()->user()->password;

        $password_actual = $request->input('password');
        $newpassword = $request->input('newpassword');

       if ( Hash::check($password_actual, $password)) { //Si la contraseña ingresada en el campo password es igual a la contraseña en la base de datos

                if ( Hash::check($newpassword, $password) ){

                $notification = "Ingrese una nueva contraseña distinta a la anterior.";
                return back()->with(compact('notification'));
                }

               else
               {
                    $user = auth()->user();
                    $user->password = bcrypt($newpassword);
                    $user->update();

                    $notification = "Contraseña cambiada exitosamente.";
                    return back()->with(compact('notification'));
               }
        }       
        else
        {
            $notification = "La contraseña ingresada como actual no corresponde a la registrada en la base de datos, por favor verifique.";
            return back()->with(compact('notification'));
        } 

       

       
    }
}

resources/views/user/Image/index.blade.php
@extends('layouts.dash')

@section('title', 'Editar foto de perfil')

@section('li2-class', 'active')

@section('styles')

<link href="{{ asset('css/estilos.css') }}" rel="stylesheet" />

<style>
    
.card-profile .card-avatar {
    margin: 10px auto 10px;
    height: 200px;
    width: 200px;
}

.card-profile{
    margin-top: 30px;
    text-align: left;
}



</style>

@endsection

@section('content')

 <div class="container-fluid">
    <div class="row">
        <div class="col-md-8">
            <div class="card card-profile">

                                 @if (session('notification'))
                                    <div class="alert alert-success">
                                        {{ session('notification') }}
                                    </div>
                                @endif

                                @if (session('alert'))
                                    <div class="alert alert-info">
                                        {{ session('alert') }}
                                    </div>
                                @endif

                                 @if (session('error'))
                                    <div class="alert alert-danger">
                                        {{ session('error') }}
                                    </div>
                                @endif

                                @if ($errors->any())
                                    <div class="alert alert-danger">
                                        <ul>
                                            @foreach ($errors->all() as $error)
                                                <li>{{ $error }}</li>
                                            @endforeach
                                        </ul>
                                    </div>
                                @endif

                   <div class="card-header" data-background-color="purple">
                    <h4 class="title">Editar imagen de perfil </h4>
                    <p class="category">"{{ $user->name }}"</p>
                   </div>
                   <div class="card-content">

                                <div class="card-avatar">
                                 
                                    <img class="img"  src="{{ $user->image_url }}" />
                                   
                                </div>


                            <form method="post" action="" enctype="multipart/form-data">

                               
                                {{ csrf_field() }}

                                <label>Actualizar foto de perfil</label>

                                <input type="file" name="foto" > 



                                   <div class="row">
                                            <div class="col-md-12">
                                                <div class="form-group">
                                                   
                                                    <div class="form-group label-floating">
                                                        <label class="control-label"> Sobre mí</label>
                                                        <textarea class="form-control" rows="5" name="description" id="decription">  {{$user->description}} 
 </textarea>
                                                    </div>
                                                </div>
                                            </div>
                                   </div>

                                    <div class="footer text-center">

                                    <button class="btn btn-primary btn-round">Actualizar información</button>
                                <a href="{{ url('User/cuenta') }}" class="btn btn-default btn-round">Volver al perfil</a>

                                   </div>

                            </form> 
                                   
                  </div> 
           </div>
         </div>

          <!--  <div class="col-md-4">
                            <div class="card card-profile">
                                
                                <div class="content">
                                    <h6 class="category text-gray"> Datos personales</h6>
                                    <h4 class="card-title">{{ $user->name }}</h4>
                                    <p class="card-content">
                                        <p> {{ $user->email }}</p>
                                    </p>
                                    <a href="{{ url('User/cuenta/foto') }}" class="btn btn-primary btn-round">editar</a>
                                </div>
                            </div>
            </div> -->
            </div>
            </div>
@endsection